apiVersion: batch/v1
kind: CronJob
metadata:
  name: send-batch-api
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-batch-api
            image: inseefrlab/onyxia-python-datascience:py3.10.9
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              cd /tmp &&
              wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/utils/send_batch.py &&
              wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/utils/send_batch.sh &&
              chmod +x send_batch.sh &&
              ./send_batch.sh
            volumeMounts:
              - name: tmp
                mountPath: "/tmp"
            env:
            - name: AWS_S3_ENDPOINT
              value: minio.lab.sspcloud.fr
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: secretKey
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-api-creds
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-api-creds
                  key: password
          restartPolicy: Never
          serviceAccountName: send-batch-api
          volumes:
          - name: tmp
            emptyDir: {}
