apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: API-Dev
spec:
  project: default
  source:
    repoURL: https://github.com/ThomasFaria/codif-ape-API.git
    targetRevision: main
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: projet-ape
  syncPolicy:
    automated:
      selfHeal: true
