"""
Lightweight validation for prediction responses returned by the inference API.

- Ensures API schema consistency with minimal overhead.
- Strong validation and normalization are performed during training
  (via `process_response` in the model artifact).
- The output contract is defined per PredictionResponse.
"""
from typing import Dict, Union

from pydantic import BaseModel, RootModel


class Prediction(BaseModel):
    code: str
    probabilite: float
    libelle: str


class PredictionResponse(RootModel[Dict[str, Union[Prediction, float, str]]]):
    pass
    """
    Contract for the normalized prediction responses generated by the model artifact.

    Expected flat structure after normalization:

    {
    "1": Prediction,
    "2": Prediction,
    ...,
    "IC": float,      # required confidence score
    "MLversion": str  # required run_id as model version
    }

    Notes:
    - The output reflects what the model artifact produces, but the API applies
    `model_dump()` in `predict()` before returning to ensure schema consistency.
    - Strong validation is performed during training; inference focuses on lightweight
    structural checks for performance.
    - Any changes to the output schema (e.g., new fields, renaming) must be documented
    both here and in training repo (codif-ape-training) to maintain API contract clarity.
    """
