apiVersion: batch/v1
kind: CronJob
metadata:
  name: etl-monitoring-test
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-monitoring
            image: inseefrlab/onyxia-python-datascience:py3.10.9
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - | 
              cd /tmp &&
              wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/utils/extract_prod_logs.py &&
              wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/utils/send_batch.py &&
              wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/utils/transform_logs.py &&
              wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/utils/etl_monitoring.sh &&
              chmod +x etl_monitoring.sh &&
              ./etl_monitoring.sh
            volumeMounts:
              - name: tmp
                mountPath: "/tmp"
            env:
            # env var for s3 connexion
            - name: AWS_S3_ENDPOINT
              value: minio.lab.sspcloud.fr
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: secretKey
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-api-creds
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-api-creds
                  key: password
          restartPolicy: Never
          serviceAccountName: etl-monitoring
          volumes:
          - name: tmp
            emptyDir: {}
